# Generated by Django 3.1.2 on 2021-03-04 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', multiselectfield.db.fields.MultiSelectField(choices=[('TLE', 'TLE'), ('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('FILIPINO', 'Filipino'), ('MAPEH', 'MAPEH'), ('SCIENCE', 'Science'), ('ESP', 'ESP'), ('AP', 'Araling Panlipunan')], max_length=46)),
                ('tuesday', multiselectfield.db.fields.MultiSelectField(choices=[('TLE', 'TLE'), ('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('FILIPINO', 'Filipino'), ('MAPEH', 'MAPEH'), ('SCIENCE', 'Science'), ('ESP', 'ESP'), ('AP', 'Araling Panlipunan')], max_length=46)),
                ('wednesday', multiselectfield.db.fields.MultiSelectField(choices=[('TLE', 'TLE'), ('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('FILIPINO', 'Filipino'), ('MAPEH', 'MAPEH'), ('SCIENCE', 'Science'), ('ESP', 'ESP'), ('AP', 'Araling Panlipunan')], max_length=46)),
                ('thursday', multiselectfield.db.fields.MultiSelectField(choices=[('TLE', 'TLE'), ('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('FILIPINO', 'Filipino'), ('MAPEH', 'MAPEH'), ('SCIENCE', 'Science'), ('ESP', 'ESP'), ('AP', 'Araling Panlipunan')], max_length=46)),
                ('friday', multiselectfield.db.fields.MultiSelectField(choices=[('TLE', 'TLE'), ('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('FILIPINO', 'Filipino'), ('MAPEH', 'MAPEH'), ('SCIENCE', 'Science'), ('ESP', 'ESP'), ('AP', 'Araling Panlipunan')], max_length=46)),
                ('saturday', multiselectfield.db.fields.MultiSelectField(choices=[('TLE', 'TLE'), ('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('FILIPINO', 'Filipino'), ('MAPEH', 'MAPEH'), ('SCIENCE', 'Science'), ('ESP', 'ESP'), ('AP', 'Araling Panlipunan')], max_length=46)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('page', models.CharField(max_length=40)),
                ('subject', models.CharField(choices=[('TLE', 'TLE'), ('MATH', 'Mathematics'), ('ENGLISH', 'English'), ('FILIPINO', 'Filipino'), ('MAPEH', 'MAPEH'), ('SCIENCE', 'Science'), ('ESP', 'ESP'), ('AP', 'Araling Panlipunan')], max_length=50)),
                ('week', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
